//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication4.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Item_table
    {
        public int Id { get; set; }
        public string prod_name { get; set; }
        public string prod_des { get; set; }
        public double prod_sbid { get; set; }
        public double prod_cbid { get; set; }
    }
}
